/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "rofi.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Empty, Empty, AUTO)


PB_BIND(Descriptor, Descriptor, AUTO)


PB_BIND(Joint, Joint, AUTO)


PB_BIND(Connector, Connector, AUTO)


PB_BIND(RofiState, RofiState, AUTO)


PB_BIND(DeviceCommand, DeviceCommand, AUTO)


PB_BIND(JointSetPosition, JointSetPosition, AUTO)


PB_BIND(JointCommand, JointCommand, AUTO)


PB_BIND(ConnectorCommand, ConnectorCommand, AUTO)


PB_BIND(RofiRequest, RofiRequest, AUTO)


PB_BIND(RofiResponse, RofiResponse, AUTO)













